### ISSUE TITLE
URS - Requirements

### ISSUE THREAD

**Issue by luudvkeulen** [luudvkeulen/Final-Fontasy-XVI#2]
Kaart requirements duidelijker
Spectators - Must

**Comment by luudvkeulen** [comment]
Scoreboard - Must
Levenspunten - Must
Text Chat - Must
Voice - Should
Server kiezen - Must
Kaart requirements duidelijker
Spectators - Must

**Comment by RobindeKort** [comment]
Servers weergeven, Servers joinen en Server joinen als spectator usecases gemaakt
